class Data:

    AVAILABLE_BUNS = 3
    AVAILABLE_INGREDIENTS = 6
    LEN_REMOVE_INGREDIENT = 0
    MOCK_BUN_PRICE_VALUE = 200
    MOCK_INGREDIENT_PRICE_VALUE = 300
    MOCK_BUN_NAME_VALUE = "white bun"
    MOCK_INGREDIENT_NAME_VALUE = "chili sauce"
    MOCK_INGREDIENT_TYPE_VALUE = "sauce"
